services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: insync_web
    ports:
      - "80:5000"  # Expose port 80 for production
    env_file:
      - .env.production
    depends_on:
      - db_prod

  db_prod:
    image: mysql:8.0
    container_name: insync_db
    env_file:
      - .env.production
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
