services:
  web:
    build: .
    container_name: insync_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://user:password@db/insync_db
    volumes:
      - ./web:/web
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: insync_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: insync_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
