services:
  web:
    build: .
    container_name: insync_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./web:/web
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: insync_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
